CREATE TABLE "orders"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    total_paid  DOUBLE PRECISION   DEFAULT 0.0  ,
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE orders_products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity  INTEGER                                 NOT NULL,
    CONSTRAINT pk_orderproduct PRIMARY KEY (id)
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    price       numeric                                  NOT NULL,
    description VARCHAR(255),
    quantity    INTEGER DEFAULT 100                     NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

ALTER TABLE orders_products
    ADD CONSTRAINT FK_ORDERPRODUCT_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE orders_products
    ADD CONSTRAINT FK_ORDERPRODUCT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERPRODUCT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);